name: argon_flutter
description: Free Flutter App Template created by Creative Tim.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio :
  fluttertoast : ^8.0.4
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  url_launcher: ^5.5.2
  scrollable_positioned_list: ^0.1.7
  file_picker: ^1.3.6
  google_fonts: ^1.1.0
  cupertino_icons: ^0.1.3
  flutter_clean_calendar: ^1.0.2+1
  date_format: ^2.0.2
  pretty_dio_logger: ^1.1.1
  intl : ^0.16.1
  event_bus: ^2.0.0
  flutter_secure_storage: ^4.2.0


dev_dependencies:
  flutter_test:
     sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/pro-background.png
   - assets/img/onboard-background.png
   - assets/img/logo-android.png
   - assets/img/logo-ios.png
   - assets/img/logo-argon.png
   - assets/img/profile-screen-avatar.jpg
   - assets/img/profile-screen-bg.png
   - assets/img/register-bg.png
   - assets/img/chat-avatar.jpeg
   - assets/img/argon-logo.png
   - assets/img/argon-logo-onboarding.png
   - assets/img/aa.png
   - assets/img/ahla.png
   - assets/img/logowhite.png
   - assets/img/bb.jpg
   - assets/img/ff.jpg
   - assets/icons/
   - assets/images/
   - assets/images/onboard-background.png
   - assets/images/bb.jpg
   - assets/images/white-care.png
   - assets/doctor_pic2.png
   - assets/mappin.png
   - assets/clock.png
   - assets/map.png
   - assets/list.png
   - assets/list.png
   - assets/images/doctor11.jpg
   - assets/ne.png
   - assets/derma.png
   - assets/salem.png
   - assets/oo.png
   - assets/scope.png
   - assets/ped.png


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600

